### ISSUE TITLE
How to get the Luna16 datasets?

### ISSUE THREAD

**Issue by DaLei001** [thylakoids/luna#1]
I'm not join the LUNA16 challenge, Could I get the LUNA16 dataset and the tutorials? and how?
If you see this, tell me the answer please. Thank you!

**Comment by thylakoids** [comment]
The [luna home](https://luna16.grand-challenge.org/) has all the datasets and the tutorials, you need register and sign in first. (You can download the datasets using this script:[luna/src2/step0_downData.py](https://github.com/thylakoids/luna/blob/master/src2/step0_downData.py))

Data preprocessing tutorial:[Full Preprocessing Tutorial](https://www.kaggle.com/gzuidhof/full-preprocessing-tutorial)
